### ISSUE TITLE
Add NSF and DARPA Logos to Sponsors

### ISSUE THREAD

**Issue by fredhohman** [poloclub/poloclub.github.io#1]
Instead of the current text-only logos for NSF and DARPA, we could use the official ones: 

https://www.nsf.gov/policies/logos.jsp
https://commons.wikimedia.org/wiki/File:DARPA_Logo.jpg

**Comment by polochau** [comment]
https://github.com/poloclub/poloclub.github.io/commit/2bb2ff0e29278922f9870fe1f9160376664f00e0
